---
- !policy
  id: cd/ansible/dev-team-2/applications
  owner: !group /cd/ansible/dev-team-2/managers
  body:
  - &test_environment
    - !host
      id: app1
      annotations:
        team: dev-team-2
        ansible: true
        location: datacenter9
        environment: test

  - !group test-apps

  - !grant
    role: !group test-apps
    members: *test_environment
      
  - &production_environment
    - !host
      id: app2
      annotations:
        team: dev-team-2
        ansible: true
        location: aws
        environment: prod
  
  - !group prod-apps

  - !grant
    role: !group prod-apps
    members: *production_environment
  
  - !permit
    role: !group /cd/ansible/dev-team-2/devs
    privileges:
        - read
        - update
    resource: !policy