---
- !policy
  id: cd/kubernetes/dev-team-3
  body:
  - !group
    id: devs

  - &dev_users
    - !user
      id: Peaches
  
  - !grant
    role: !group devs
    members: *dev_users
  
  - !group
    id: managers

  - &manager_users
    - !user
      id: Johnny

  - !grant
    role: !group managers
    members: *manager_users